describe('My First Test', () => {
  it('Visits the wordball website', () => {
    cy.visit('localhost:3000')
    cy.get('#playbutton').click()
    cy.get('#canvas').click(450, 850)
    cy.get('#canvas').click('bottom')
    cy.get('#canvas').click('bottom')
    cy.get('#canvas').click('bottom')
    cy.get('#canvas').click('bottom')
    cy.get('#canvas').click('bottom')
    cy.get('#canvas').click(400, 600)
    cy.get('#canvas').click('center')
    cy.wait(1700)
    cy.get('#canvas').click(400, 600)
    cy.get('#canvas').click('center')
    cy.wait(1700)
    cy.get('#canvas').click(400, 600)
    cy.get('#canvas').click('center')
  })
})
