describe('Gameplay testing', () => {
  context('Letter order: I, V, H, I, R, A, O, F, P, L, X, M, K, E, A, X, J, R, H, Z', () => {
    it('Scoring the first five balls in x1 hole scores 9', () => {
      cy.visit('localhost:3000')
      cy.get('#playbutton').click()
      cy.get('#score').invoke('text').should('eq', 'Current Score: 0')
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center')
      cy.wait(1550)
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center')
      cy.wait(1550)
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center')
      cy.get('#score').invoke('text').should('eq', 'Current Score: 4')
      cy.wait(1550)
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center')
      cy.wait(1550)
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center')
      cy.wait(1550)
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center')
      cy.wait(1000)
      cy.get('#score').invoke('text').should('eq', 'Current Score: 9')
      // cy.contains('V').click()
    })

    it('Scoring the first five balls in x2 hole scores 18', () => {
      cy.visit('localhost:3000')
      cy.get('#playbutton').click()
      cy.get('#score').invoke('text').should('eq', 'Current Score: 0')
      cy.get('#canvas').click(310, 600)
      cy.get('#canvas').click('center')
      cy.wait(1550)
      cy.get('#canvas').click(310, 600)
      cy.get('#canvas').click('center')
      cy.wait(1550)
      cy.get('#canvas').click(310, 600)
      cy.get('#canvas').click('center')
      cy.get('#score').invoke('text').should('eq', 'Current Score: 8')
      cy.wait(1550)
      cy.get('#canvas').click(310, 600)
      cy.get('#canvas').click('center')
      cy.wait(1550)
      cy.get('#canvas').click(310, 600)
      cy.get('#canvas').click('center')
      cy.wait(1550)
      cy.get('#canvas').click(310, 600)
      cy.get('#canvas').click('center')
      cy.wait(1000)
      cy.get('#score').invoke('text').should('eq', 'Current Score: 18')
      // cy.contains('V').click()
    })

    // it('Banking letters carries them through to next round', () => {
    //   cy.visit('localhost:3000')
    //   cy.get('#playbutton').click()
    //   cy.get('#canvas').click(450, 850)
    //   cy.get('#canvas').click('bottom')
    //   cy.get('#canvas').click('bottom')
    //   cy.get('#canvas').click('bottom')
    //   cy.get('#canvas').click('bottom')
    //   cy.get('#canvas').click('bottom')
    // })


  })
})
