describe('Gameplay testing', () => {
  context('First 8 letters order: C I A T D G O A', () => {
    it('Scoring the first five balls in x1 hole scores 9', () => {
      cy.visit('localhost:3000')
      cy.get('#playbutton').click()
      cy.get('#score').invoke('text').should('eq', 'Current Score: 0')
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.wait(1550)
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.wait(1550)
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.get('#score').invoke('text').should('eq', 'Current Score: 4')
      cy.wait(1550)
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.wait(1550)
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.wait(1550)
      cy.get('#canvas').click(400, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.wait(1000)
      cy.get('#score').invoke('text').should('eq', 'Current Score: 9')
    })

    it('Scoring the first five balls in x2 hole scores 18', () => {
      cy.visit('localhost:3000')
      cy.get('#playbutton').click()
      cy.get('#score').invoke('text').should('eq', 'Current Score: 0')
      cy.get('#canvas').click(330, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.wait(1550)
      cy.get('#canvas').click(330, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.wait(1550)
      cy.get('#canvas').click(330, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.get('#score').invoke('text').should('eq', 'Current Score: 8')
      cy.wait(1550)
      cy.get('#canvas').click(330, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.wait(1550)
      cy.get('#canvas').click(330, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.wait(1550)
      cy.get('#canvas').click(330, 600)
      cy.get('#canvas').click('center', { force: true })
      cy.wait(1000)
      cy.get('#score').invoke('text').should('eq', 'Current Score: 18')
    })

    it('Banking letters carries them through to next round, valid words submit, invalid words do not', () => {
      cy.visit('localhost:3000')
      cy.get('#playbutton').click()
      cy.get('#canvas').click(450, 850)
      cy.get('#canvas').click('bottom')
      cy.get('#canvas').click('bottom')
      cy.get('#canvas').click('bottom')
      cy.get('#canvas').click('bottom')
      cy.get('#canvas').click('bottom')
      cy.get('#canvas').click('bottom')
      cy.get('#canvas').click('bottom')
      cy.wait(1500)
      cy.get('#bankedletters').invoke('attr', 'value').should('eq', 'CIATDGOA')
      cy.contains('D').click()
      cy.contains('I').click()
      cy.contains('G').click()
      cy.get('#typearea').invoke('text').should('eq', 'DIG')
      cy.get('#verifybutton').click()
      cy.get('#typearea').invoke('text').should('eq', '')
      cy.get('#score').invoke('text').should('eq', 'Current Score: 5')
      cy.get('#validwordslist').invoke('text').should('eq', 'DIG')
      cy.contains('A').click()
      cy.contains('T').click()
      cy.get('#typearea').invoke('text').should('eq', 'AT')
      cy.get('#verifybutton').click()
      cy.get('#typearea').invoke('text').should('eq', 'AT')
      cy.get('#score').invoke('text').should('eq', 'Current Score: 5')
      cy.get('#validwordslist').invoke('text').should('eq', 'DIG')
      cy.get('#clearbutton').click()
      cy.get('#typearea').invoke('text').should('eq', '')
      cy.contains('O').click()
      cy.contains('A').click()
      cy.contains('T').click()
      cy.get('#verifybutton').click()
      cy.get('#score').invoke('text').should('eq', 'Current Score: 8')
      cy.get('#validwordslist').invoke('text').should('eq', 'DIG - OAT')
    })

    it('Banking fewer than 3 letters skips the word game', () => {
      cy.visit('localhost:3000')
      cy.get('#playbutton').click()
      cy.get('#canvas').click(450, 850)
      cy.get('#canvas').click('bottom')
      cy.get('#scoreboard').should('not.be.visible')
      cy.wait(14000)
      cy.get('#scoreboard').should('be.visible')
      cy.get('#gamediv').should('not.be.visible')
    })
  })
})
